### ISSUE TITLE
Installation instructions, mysql version

### ISSUE THREAD

**Issue by Chris927** [wsaqaf/mecodify#2]
The installation instructions are referring to "mysql 14.0 or higher".

The highest (open source) version of MySQL seems to be `5.7.18`, and there is a preview release `8.0.0` mentioned, but I can't find details about version 14 or higher.

Could you please clarify installation instructions in this regard, or point me to more information.

**Comment by wsaqaf** [comment]
Dear sir,

Thank you for spotting the typo. It was meant distribution 5.5 or higher.

Sincerely,

Mecodify

**Comment by Chris927** [comment]
Perfect, thank you!
