### ISSUE TITLE
Passwords are stored plain text

### ISSUE THREAD

**Issue by matnel** [wsaqaf/mecodify#6]
The member passwords are stored plain text, not hashed.

As some people might be reusing passwords across various systems or use same patterns of passwords, plain-text storing is strongly inadvisable.

I strongly recommend to [hash](https://www.php.net/manual/en/faq.passwords.php) member passwords.

**Comment by wsaqaf** [comment]
Thanks for your comment matnel. 

There is ongoing work on a new version that has that covered: https://github.com/wsaqaf/mecodify2 

You are welcome to try it out and provide feedback.
